//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.04.15 at 12:00:06 PM ICT 
//


package com.bean;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Db }
     * 
     */
    public Db createDb() {
        return new Db();
    }

    /**
     * Create an instance of {@link Db.Products }
     * 
     */
    public Db.Products createDbProducts() {
        return new Db.Products();
    }

    /**
     * Create an instance of {@link Db.Categories }
     * 
     */
    public Db.Categories createDbCategories() {
        return new Db.Categories();
    }

    /**
     * Create an instance of {@link Db.Products.Product }
     * 
     */
    public Db.Products.Product createDbProductsProduct() {
        return new Db.Products.Product();
    }

    /**
     * Create an instance of {@link Db.Categories.Category }
     * 
     */
    public Db.Categories.Category createDbCategoriesCategory() {
        return new Db.Categories.Category();
    }

}
